name: CD

on:
  push:
    branches: ['main']
    paths-ignore:
      - '*.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ticklabvn/ssps-fe
  ORG_USERNAME: ${{ github.actor }}
      
permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          pull-request-header: 'Bot (:robot:) requested to create a new release on ${{ github.ref_name }}'

  build:
    name: Build
    needs: [release]
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.build == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env file
        run: |
          echo VITE_BACKEND_URL=${{ vars.BACKEND_URL }} >> .env
          echo VITE_GOOGLE_OAUTH_REDIRECT_URL=${{ vars.GOOGLE_OAUTH_REDIRECT_URL }} >> .env
          echo VITE_GOOGLE_CLIENT_ID=${{ vars.GOOGLE_CLIENT_ID }} >> .env

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ORG_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
  
          script: |
            export CR_PAT=${{ secrets.GITHUB_TOKEN }}
            echo $CR_PAT | docker login ${{ env.REGISTRY }} -u ${{ env.ORG_USERNAME }} --password-stdin
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

            cd ssps-fe
            export TOKEN=${{ secrets.CURL_TOKEN }}
            curl -s https://$TOKEN@raw.githubusercontent.com/ticklabvn/ssps-fe/main/docker-compose.yml -o docker-compose.yml
            docker compose stop ssps-fe
            docker compose rm -f ssps-fe
            docker compose up -d ssps-fe
            docker logout ${{ env.REGISTRY }}