name: CI

on:
  pull_request:
    branches: ['main']
    paths-ignore:
      - '*.md'
jobs:
  ci:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Setup env file
        run: |
          echo VITE_BACKEND_URL=${{ vars.BACKEND_URL }} >> .env
          echo VITE_GOOGLE_OAUTH_REDIRECT_URL=${{ vars.GOOGLE_OAUTH_REDIRECT_URL }} >> .env
          echo VITE_GOOGLE_CLIENT_ID=${{ vars.GOOGLE_CLIENT_ID }} >> .env

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build