name: Production

on:
  push:
    branches: ['main']
    paths-ignore:
      - '*.md'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ticklabvn/ssps-fe
  ORG_USERNAME: ${{ github.actor }}

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          pull-request-header: 'Bot (:robot:) requested to create a new release on ${{ github.ref_name }}'

  build:
    name: Build
    needs: [release]
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.build == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env file
        run: |
          echo VITE_BACKEND_URL=${{ vars.BACKEND_URL }} >> .env

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ORG_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.release.outputs.tag_name }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    name: Deploy production
    runs-on: self-hosted
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: start nginx
        run: |
          export CR_PAT=${{ secrets.GITHUB_TOKEN }}
          echo $CR_PAT | docker login ${{ env.REGISTRY }} -u ${{ env.ORG_USERNAME }} --password-stdin
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

          docker compose stop ssps-fe
          docker compose rm -f ssps-fe
          docker compose up -d ssps-fe
          docker logout ${{ env.REGISTRY }}